name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn install --immutable
      env:
        YARN_CHECKSUM_BEHAVIOR: update
    - name: Build
      run: ./node_modules/.bin/microbundle build --no-compress --jsx React.createElement
    - name: Publish
      run: npm publish